### ISSUE TITLE
File organization

### ISSUE THREAD

**Issue by smburdick** [Puget-Sound-Bitmaps/bitmap-engine#2]
- `BitmapWorkloadGenerator/` is fine since it's just a few Java files we probably won't be working with much anyway.
- `BitmapEngine/src` has too many files to be comprehended easily. Files should be separated into logical subdirectories.
- The test files should be placed in `tst/`
- There are a couple ways we could organize the source files. We could organize them by algorithm (WAH, VAL, BBC, etc), which is my preference, or by functionality (compressor/query).

Suggested format:
```
BitmapEngine/
    src/
        main.c
        Makefile
        wah/
        writer/
        util/
           clock/
        [...]
    tst/ 
```

**Comment by Jahrme** [comment]
I agree with most of your post. However, I think that the `Makefile`s should **not** be in the `src/` directories (as they are not “source”, per se). I also think that, when compiling, it would be helpful to place the binary output files in `bin/` directories entirely ignored by Git. Additionally, I think that having a nicely structured `doc/` directory (which would encompass the contents of the current `FSM/`, `images/`, and `uml/` directories, as well as parts of the README) would benefit the project, especially as this would allow easy display of documentation using GitHub Pages.

While thinking about the project this is (roughly) what I imagine the full repo structure looking like:
```
Bitmap-Engine/
    .gitignore
    Makefile
    README.md
    BitmapEngine/
        Makefile
        src/
            main.c
            wah/
            writer/
            util/
                clock/
            [...]
        tst/
            [...]
        bin/
            main
            main.o
            [...]
    BitmapWorkloadGenerator
        Makefile
        src/
            [...]
        bin/
            [...]
    doc/
        [All documentation other than source comments]
        [e.g., UML diagrams, FSM diagrams, instructions, etc.]
        [...]
```

**Comment by smburdick** [comment]
I think that's a good point on the `Makefile`, but we shouldn't need one at the top level. I think a better home for the documentation is on the wiki. I will close this issue once I finish organizing the code and submit a pull request.

**Comment by Jahrme** [comment]
The top level `Makefile` is mostly just a usage convenience (it would call both lower level `Makefile`s) as then from the repository root you can just run `make` to have it handle both creating data and running the Bitmap Engine.
